### ISSUE TITLE
main failing lint/unit tests for make

### ISSUE THREAD

**Issue by dpeterka** [aws-observability/aws-otel-collector#1174]
**Describe the bug**
make package-rpm fails

**Steps to reproduce**
```
FROM amazonlinux:2
COPY . /app
RUN yum groupinstall -y "Development Tools" &&\
    yum install -y wget

RUN wget --no-check-certificate https://go.dev/dl/go1.17.9.linux-amd64.tar.gz &&\
    tar -C /usr/local -xzf go1.17.9.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
```
`make package-rpm`

**What did you expect to see?**
An RPM

**What did you see instead?**
```
pkg/logger/logger.go:42:10: cannot use &lumberjack.Logger{...} (type *lumberjack.Logger) as type lumberjack.Logger in return argument
pkg/logger/logger.go:50:2: cannot use nil as type lumberjack.Logger in return argument
pkg/logger/logger.go:58:23: invalid operation: lumberjackLogger == nil (mismatched types lumberjack.Logger and nil)
pkg/logger/logger.go:73:101: cannot use lumberjackLogger (type lumberjack.Logger) as type io.Writer in argument to zapcore.AddSync:
	lumberjack.Logger does not implement io.Writer (Write method has pointer receiver)
pkg/logger/logger.go:81:22: invalid operation: lumberjackLogger != nil (mismatched types lumberjack.Logger and nil)
pkg/logger/logger.go:87:10: cannot use lumberjackLogger (type lumberjack.Logger) as type io.WriteCloser in assignment:
	lumberjack.Logger does not implement io.WriteCloser (Close method has pointer receiver)
```

**Environment**
Default for this repo on main branch

**Additional context**
Static Check is out of. date in the make filem, appears dependabot doesn't notice.  I updated staticcheck@latest in Makefile to work around it not supporting current unit test (note this was go 1.18 on my initial tests.

**Comment by bryan-aguilar** [comment]
Currently there is a known limitation with building the `ADOT Collector` with go version `1.18`. We are currently pinning to `~1.17` until the upstream dependency issue is resolved. Have you tried to build on with go `1.17`?

**Comment by dpeterka** [comment]
> Currently there is a known limitation with building the `ADOT Collector` with go version `1.18`. We are currently pinning to `~1.17` until the upstream dependency issue is resolved. Have you tried to build on with go `1.17`?

I tried 1.18 and the error posted was from 1.17.9 I see in builds you're on 1.17.2 but haven't tried that as yet.

**Comment by bryan-aguilar** [comment]
I definitely may have been mistaken from my first read. I have taken this on and will look into it on our end. I will get back to you on this issue when I have any updates. Thank you for the reproducibility steps!

**Comment by Aneurysm9** [comment]
```
pkg/logger/logger.go:42:10: cannot use &lumberjack.Logger{...} (type *lumberjack.Logger) as type lumberjack.Logger in return argument
```

This error does not make any sense.  [That function](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/logger/logger.go#L40) declares `*lumberjack.Logger` as the return type and hasn't changed in the last year.  

I'm not able to reproduce this issue from the HEAD of the `main` branch.  Can you please provide any details about local modifications that may have been made?
